function hMain = blinkGUI()
%LATER
% > have a window with version info, my name, website, etc.
% > help documentation --> send to website, contact info
% > uimenu, uitoolbar --> have different menus and toolbars?
% > windows path joining... will need to change some hard-coded things
% > logging: how to set a location for log file?
% > specs file? 
% > what to do upon closing the figure? (delete GUIDATA, etc)
% > add 'TooltipString' properties for each item?
% > add 'UIContextMenu'?
% > memory considerations: what should happen when you toggle between
%   analyses? reset things?

%FUNCTIONALITY TO ADD
% > scroll through things plotted within the GUI
%       > sort PSTH data by density/by original order
%       > only plot a few subjects if there's more than one ref set
%       > scroll through the plots of raw blink data
%   	> scroll through the plots of PSTH data
% > plot everything when it's popped out? consider revamping that subfxn
% > write a data quality script - check things before running analyses?
% > warnings about no significant blink inhibition (permutation test at
%   floor) -- from GUI and in summary file?


%SMALLER BUGS/THINGS TO FIX
% > position the figures next to the GUI
% > toggleBigButtons - can I prevent user from updating other things in the
%   GUI while analyses are running?
% > add subject order to PSTH, now that 3 column format is an option?
% > add filenames to BLINKMOD output


%GENERAL NOTES:
% > input specs have changed slightly: subjects should each have a
%   column, and frames should be in rows (better for excel limits).
% > think about upper limits for data that we can process -- how many
%   frames? subjects? (think about excel limitations for printing out data)
% > standardize language/terms ("sample" rather than "frame", etc)


%%

DEV = true;


%% Initialize GUIDATA
%this is a class containing a bunch of default settings 
GUIDATA = BlinkGuiData;

%% GUI

%MAIN FIGURE
%Parent figure width and height
W=580;
H=740;

inputPanelPosition = [10, 200, (W-20), 230];

%Color settings
bkgdColor = [215 230 235] ./256;
inputPanelColor = bkgdColor; % [230 230 230] ./256;
buttonColor = [180 250 150] ./ 256;

hMain = figure(...
    'units','pixels',...
    'position',[100 100 W H],...
    'MenuBar', 'none',...
    'Toolbar','none',...
    'HandleVisibility','callback',... 
    'numbertitle','off',...
    'name', 'Blink Analyses',...
    'resize', 'off',...
    'Color',bkgdColor,...
    'CloseRequestFcn',{@cbCloseGUI GUIDATA},...
    'Visible', 'off');

%
if DEV
    guidata(hMain, GUIDATA);
    set(hMain, 'HandleVisibility', 'on');
end



%TODO - is this okay for executable?? 
set(get(hMain,'Parent'),...
    'DefaultUicontrolFontName', 'Helvetica',... DefaultUicontrolFontName?
    'DefaultUicontrolFontSize', 15,...
    'DefaultUicontrolFontUnits', 'pixels',...
    'DefaultUicontrolFontWeight', 'normal',...
    'DefaultUicontrolHorizontalAlignment', 'left');

%Can I set defaults for input/warning/error dialogs?


%% ELEMENTS FOR BOTH ANALYSES

%Buttons to toggle between analyses
uicontrol(hMain, 'Tag', 'hPermToggle',...
    'Style', 'toggle', ...
    'String', 'Blink Modulation',...
    'FontSize', 18,...
    'Position', [0 H-35, W/2, 35],...
    'Callback', {@cbAnalysisToggle GUIDATA 'perm'});

uicontrol(hMain, 'Tag', 'hPsthToggle', ...
    'Style', 'toggle', ...
    'String', 'Peri-stimulus time histogram',...
    'FontSize', 18,...
    'Position', [W/2 H-35 W/2 35],...
    'Callback', {@cbAnalysisToggle GUIDATA 'psth'});

% Axes to plot selected data
axes('Parent',hMain, 'Tag', 'hPlotAxes',...
    'Units', 'pixels', ...
    'FontName', 'Helvetica',...
    'FontSize', 12,...
    'HandleVisibility','callback', ...
    'Position',[50 (H-280) (W-100) 200]);

% Button to pop out figure
% TODO - fix this/make it a button press in axis
uicontrol(hMain,...
    'Style', 'pushbutton',...
    'String', 'pop',...
    'Position', [W-50 630 40 40],...
    'Callback', {@cbPopOutGuiPlot GUIDATA});

%% BLINK PERM INPUTS

%MAIN INPUT PANEL
hPermInputPanel = uipanel('Parent', hMain, 'Tag', 'hPermInputPanel',...
             'Title','Inputs',...
             'FontSize', 15,...
             'BackgroundColor', inputPanelColor,...
             'Units', 'pixels',...
             'Position', inputPanelPosition);

%LOAD BLINK CSV LABEL
uicontrol(hPermInputPanel,...
    'Style', 'text',...
    'String','Load Data (.csv file)',...
    'FontWeight', 'bold',...
    'HorizontalAlignment', 'left',...
    'Units','pixels',...
    'Position',[10 150 250 20],...
    'BackgroundColor', inputPanelColor);

% Button that brings up menu to select a file, + related dialog boxes
uicontrol(hPermInputPanel, 'Tag', 'hLoadBlinkFile',...
    'Style','pushbutton',...
    'String','Raw Blinks',...
    'Units','pixels',...
    'Position',[160 145 95 30],...
    'Callback', {@cbLoadBlinks GUIDATA}); 

% NUMBER OF PERMUTATIONS
% Label
uicontrol(hPermInputPanel,...
    'Style','text',...
    'String','Number of Permutations:',...
    'FontWeight','bold',...
    'Units','pixels',... 
    'Position',[10 70 190 25],...
    'BackgroundColor',inputPanelColor);

% Editable text box where number of permutations is entered
uicontrol(hPermInputPanel, 'Tag', 'hNumPerms',...
    'Style','edit',...
    'HorizontalAlignment', 'center',...
    'BackgroundColor','white',...
    'Units','pixels',...
    'Position',[200 72 70 25]);

% RESET INPUTS button
uicontrol(hPermInputPanel, 'Tag', 'hPermReset',...
    'Style','pushbutton',...
    'String','Reset Inputs',...
    'ForegroundColor', 'white',...
    'FontWeight','bold',...
    'Units','pixels',...
    'BackgroundColor',[250 80 80]./256,...
    'Position',[5 5 100 25],...
    'Callback', {@resetPerm GUIDATA}); 


%% PERMS ADVANCED OPTIONS PANEL
hPermsAdvPanel = uipanel('Parent',hPermInputPanel, 'Tag', 'hPermsAdvPanel',...
            'Title','Advanced Options',...
            'FontSize', 15,...
            'BackgroundColor',inputPanelColor,...
            'Units', 'pixels',...
            'Position',[300, 10, 250, 200]); 

%W VALUE
%Label - smoothing parameter
uicontrol(hPermsAdvPanel,...
    'Style', 'text',...
    'String','Smoothing (Gaussian kernel)',...
    'FontWeight', 'bold',...
    'HorizontalAlignment', 'left',...
    'Units','pixels',...
    'Position',[10 150 230 25],...
    'BackgroundColor', inputPanelColor);

%Label - W range
uicontrol(hPermsAdvPanel,...
    'Style', 'text',...
    'String','W Range ',...
    'HorizontalAlignment', 'left',...
    'Units','pixels',...
    'Position',[30 120 80 25],...
    'BackgroundColor', inputPanelColor);

%Edit W range
uicontrol(hPermsAdvPanel, 'Tag', 'hWRange',...
    'Style', 'edit',...
    'String','',...
    'HorizontalAlignment', 'center',...
    'BackgroundColor','white',...
    'Units','pixels',...
    'Position',[100 122 80 25]);


%SIGNIFICANCE THRESHOLDS
uicontrol(hPermsAdvPanel,...
    'Style', 'text',...
    'String','Significance Thresholds (0 - 100)',...
    'FontWeight', 'bold',...
    'HorizontalAlignment', 'left',...
    'Units','pixels',...
    'Position',[10 45 230 20],...
    'BackgroundColor', inputPanelColor);
    
%Label - low significance threshold
uicontrol(hPermsAdvPanel,...
    'Style', 'text',...
    'String','Low ',...
    'HorizontalAlignment', 'left',...
    'Units','pixels',...
    'Position',[30 15 35 25],...
    'BackgroundColor', inputPanelColor);

%Edit low significance threshold
uicontrol(hPermsAdvPanel, 'Tag', 'hSigLowPerm',...
    'Style', 'edit',...
    'String','2.5',...
    'HorizontalAlignment', 'center',...
    'Units','pixels',...
    'Position',[67 17 40 25],...
    'BackgroundColor','white');

%Label - high significance threshold
uicontrol(hPermsAdvPanel,...
    'Style', 'text',...
    'String','High ',...
    'HorizontalAlignment', 'right',...
    'Units','pixels',...
    'Position',[130 15 35 25],...
    'BackgroundColor',inputPanelColor);
 
%Edit high significance threshold
uicontrol(hPermsAdvPanel, 'Tag', 'hSigHighPerm',...
    'Style', 'edit',...
    'String','97.5',...
    'HorizontalAlignment', 'center',...
    'Units','pixels',...
    'Position',[170 17 40 25],...
    'BackgroundColor','white');


%% BLINK PSTH ITEMS

%MAIN INPUT PANEL
hPsthInputPanel = uipanel('Parent',hMain, 'Tag', 'hPsthInputPanel',...
             'Title','Inputs',...
             'FontSize', 15,...
             'BackgroundColor',inputPanelColor,...
             'Units', 'pixels',...
             'Position', inputPanelPosition,...
             'Visible','off');

%LOAD DATA LABEL
uicontrol(hPsthInputPanel,...
    'Style', 'text',...
    'String','Load Data (.csv files)',...
    'FontWeight', 'bold',...
    'HorizontalAlignment', 'left',...
    'Units','pixels',...
    'Position',[10 180 250 20],...
    'BackgroundColor', inputPanelColor);


% LOAD TARGET EVENTS
% Button that brings up menu to select a file, + related dialog boxes
uicontrol(hPsthInputPanel, 'Tag', 'hLoadTargetEvents',...
    'Style','pushbutton',...
    'String','Target Events',...
    'Units','pixels',...
    'Position',[14 150 120 30],...
    'Callback', {@cbLoadTargetData GUIDATA}); 

%LOAD REFERENCE EVENTS
% Button that brings up menu to select a file, + related dialog boxes
uicontrol(hPsthInputPanel, 'Tag', 'hLoadRefEvents',...
    'Style','pushbutton',...
    'String','Reference Events',...
    'Units','pixels',...
    'Position',[139 150 130 30],...
    'Callback', {@cbLoadRefData GUIDATA}); 
         
%LAG SIZE
uicontrol(hPsthInputPanel,...
    'Style', 'text',...
    'String','Window Size (# samples)',...
    'FontWeight', 'bold',...
    'HorizontalAlignment', 'left',...
    'Units','pixels',...
    'Position',[10 115 250 20],...
    'BackgroundColor', inputPanelColor);
    
%Label - Before
uicontrol(hPsthInputPanel,...
    'Style', 'text',...
    'String','Before event ',...
    'HorizontalAlignment', 'right',...
    'Units','pixels',...
    'Position',[14 80 95 25],...
    'BackgroundColor', inputPanelColor);

%Label - After
uicontrol(hPsthInputPanel,...
    'Style', 'text',...
    'String','After event ',...
    'HorizontalAlignment', 'right',...
    'Units','pixels',...
    'Position',[140 80 95 25],...
    'BackgroundColor',inputPanelColor);

%Edit window size before event
uicontrol(hPsthInputPanel,  'Tag', 'hLagBefore',...
    'Style', 'edit',...
    'String','',...
    'HorizontalAlignment', 'center',...
    'Units','pixels',...
    'Position',[115 82 30 25],...
    'BackgroundColor','white');

%Edit window size after event
uicontrol(hPsthInputPanel, 'Tag', 'hLagAfter',...
    'Style', 'edit',...
    'String','',...
    'HorizontalAlignment', 'center',...
    'Units','pixels',...
    'Position',[241 82 30 25],...
    'BackgroundColor','white');


% NUMBER OF PERMUTATIONS
% Label
uicontrol(hPsthInputPanel,...
    'Style','text',...
    'Units','pixels',... 
    'Position',[10 40 190 25],...
    'FontWeight','bold',...
    'String','Number of Permutations:',...
    'BackgroundColor',inputPanelColor);

% Editable text box where number of permutations is entered
uicontrol(hPsthInputPanel, 'Tag', 'hNumPermsPsth',...
    'Style','edit',...
    'HorizontalAlignment', 'center',...
    'BackgroundColor','white',...
    'Units','pixels',...
    'Position',[200 42 70 25]);


% RESET INPUTS button
uicontrol(hPsthInputPanel, 'Tag', 'hPsthReset',...
    'Style','pushbutton',...
    'String','Reset Inputs',...
    'ForegroundColor', 'white',...
    'FontWeight','bold',...
    'Units','pixels',...
    'BackgroundColor',[250 80 80]./256,...
    'Position',[5 5 100 25],...
    'Callback', {@resetPsth GUIDATA}); 
         
%% PSTH ADVANCED OPTIONS PANEL
hPsthAdvPanel = uipanel('Parent',hPsthInputPanel, 'Tag', 'hPsthAdvPanel',...
            'Title','Advanced Options',...
            'FontSize', 15,...
            'BackgroundColor',inputPanelColor,...
            'Units', 'pixels',...
            'Position',[300, 10, 250, 200]); 

%PSTH settings
uicontrol(hPsthAdvPanel,...
    'Style', 'text',...
    'String','PSTH Settings',...
    'FontWeight', 'bold',...
    'HorizontalAlignment', 'left',...
    'Units','pixels',...
    'Position',[10 150 120 25],...
    'BackgroundColor', inputPanelColor);

%label for start frame
uicontrol(hPsthAdvPanel,...
    'Style', 'text',...
    'String','Reference start frame',...
    'HorizontalAlignment', 'left',...
    'Units','pixels',...
    'Position',[30 120 150 25],...
    'BackgroundColor', inputPanelColor);

%Edit start frame
uicontrol(hPsthAdvPanel, 'Tag', 'hStartFrameEdit',...
    'Style', 'edit',...
    'String','1',...
    'HorizontalAlignment', 'center',...
    'BackgroundColor','white',...
    'Units','pixels',...
    'Position',[185 122 45 25]);

%label for include threshold
uicontrol(hPsthAdvPanel,...
    'Style', 'text',...
    'String','Include threshold',...
    'HorizontalAlignment', 'left',...
    'Units','pixels',...
    'Position',[30 85 150 25],...
    'BackgroundColor', inputPanelColor);

%Edit include threshold
uicontrol(hPsthAdvPanel, 'Tag', 'hInclThreshEdit',...
    'Style', 'edit',...
    'String','0.2',...
    'HorizontalAlignment', 'center',...
    'BackgroundColor','white',...
    'Units','pixels',...
    'Position',[185 87 45 25]);


%SIGNIFICANCE THRESHOLDS
uicontrol(hPsthAdvPanel,...
    'Style', 'text',...
    'String','Significance Thresholds (0 - 100)',...
    'FontWeight', 'bold',...
    'HorizontalAlignment', 'left',...
    'Units','pixels',...
    'Position',[10 45 230 20],...
    'BackgroundColor', inputPanelColor);
    
%Label - low significance threshold
uicontrol(hPsthAdvPanel,...
    'Style', 'text',...
    'String','Low ',...
    'HorizontalAlignment', 'left',...
    'Units','pixels',...
    'Position',[30 15 35 25],...
    'BackgroundColor', inputPanelColor);

%Edit low significance threshold
uicontrol(hPsthAdvPanel, 'Tag', 'hSigLowPsth',...
    'Style', 'edit',...
    'String','2.5',...
    'HorizontalAlignment', 'center',...
    'Units','pixels',...
    'Position',[67 17 40 25],...
    'BackgroundColor','white');

%Label - high significance threshold
uicontrol(hPsthAdvPanel,...
    'Style', 'text',...
    'String','High ',...
    'HorizontalAlignment', 'right',...
    'Units','pixels',...
    'Position',[130 15 35 25],...
    'BackgroundColor',inputPanelColor);
 
%Edit high significance threshold
uicontrol(hPsthAdvPanel, 'Tag', 'hSigHighPsth',...
    'Style', 'edit',...
    'String','97.5',...
    'HorizontalAlignment', 'center',...
    'Units','pixels',...
    'Position',[170 17 40 25],...
    'BackgroundColor','white');


%% OUTPUT PANEL (both analyses)
hOutputPanel = uipanel('Parent',hMain,...
     'Title','Outputs',...
     'FontSize', 15,...
     'BackgroundColor',bkgdColor,...
     'Units','pixels',...
     'Position',[10, 55, (W-20), 140]);

%Label for checkboxes
uicontrol(hOutputPanel,...
    'Style', 'text',...
    'String', 'Files to save:',...
    'FontWeight', 'bold',...
    'HorizontalAlignment', 'left',...
    'BackgroundColor', bkgdColor,...
    'Units', 'pixels',...
    'Position', [10 85 100 25]);

%check box - save summary
uicontrol(hOutputPanel,...
    'Style', 'checkbox',...
    'String', 'Summary csv',...
    'BackgroundColor', bkgdColor,...
    'Value', 1,...
    'Units', 'pixels',...
    'Position', [120 85 120 30],...
    'Callback', {@cbCheckSaveCsv GUIDATA});

%check box - save figures
uicontrol(hOutputPanel,...
    'Style', 'checkbox',...
    'string', 'Figures',...
    'BackgroundColor', bkgdColor,...
    'Value', 1,...
    'Units', 'pixels',...
    'Position', [260 85 80 30],...
    'Callback', {@cbCheckSaveFigs GUIDATA});

hFigFormat = uicontrol(hOutputPanel, 'Tag', 'hFigFormat',...
    'Style', 'popup',...
    'String', 'jpg|pdf|eps|fig|png|tif',...
    'Position', [335 82 80 30],...
    'Callback', {@cbChooseFigFormat GUIDATA});

%check box - save mat file
uicontrol(hOutputPanel,...
    'Style', 'checkbox',...
    'string', '.mat file',...
    'BackgroundColor', bkgdColor,...
    'Value', 1,...
    'Units', 'pixels',...
    'Position', [430 85 100 30],...
    'Callback', {@cbCheckSaveMat GUIDATA});

         
%TYPE NAME OF OUTPUT FILE - TODO change to file prefix in code
%Label for edit box where output filename can be entered
uicontrol(hOutputPanel,...
    'Style','text',...
    'Units','pixels',...
    'Position',[10 50 160 25],...
    'FontWeight','bold',...
    'String','Prefix for output files:',...
    'BackgroundColor',bkgdColor);

%Editable text box where output filename is entered
uicontrol(hOutputPanel, 'Tag', 'hOutputFile',...
    'Style','edit',...
    'String','',...
    'HorizontalAlignment','center',...
    'BackgroundColor', 'white',...
    'Units','pixels',...
    'Position',[210 50 200 30]);

%Output directory
uicontrol(hOutputPanel, 'Tag', 'hChooseOutputDir',...
    'Style','pushbutton',...
    'String','Choose output directory',...
    'Units','pixels',...
    'Position',[10 10 180 30],...
    'Callback', {@cbChooseOutputDir GUIDATA});

% Label where output directory is displayed
uicontrol(hOutputPanel, 'Tag', 'hListOutputFile',...
    'Style','text',...
    'HorizontalAlignment', 'center',...
    'Units','pixels',...
    'Position',[210 15 320 20],...
    'String','none selected',...
    'FontAngle','italic');


%% ANALYZE BUTTON
%Button to run the analysis
hGoButton = uicontrol(hMain, 'Tag', 'hGoButton',...
    'Style','pushbutton',...
    'String','Run Analysis',...
    'FontWeight','bold',...
    'BackgroundColor', buttonColor,...
    'Units','pixels',...
    'Position',[(W/2-60) 15 120 30],...
    'FontSize',16);

%% Final steps to initialize

% Create handles structure in GUIDATA
GUIDATA.setHandles(hMain);

% Set default analysis ('perm' or 'psth')
cbAnalysisToggle([],[], GUIDATA, 'psth');

% Set default figure format
cbChooseFigFormat(hFigFormat, [], GUIDATA);

% Make GUI visible
drawnow
set(hMain,'Visible', 'on');

%% Callback functions (only called from GUI)

% Pop out whatever is plotted in the embedded axis
function cbPopOutGuiPlot(~, ~, gd)
    h = figure('Position', [50 50 800 400]);
    a = copyobj(gd.handles.hPlotAxes, h);
    set(a, 'units','normalized',...
        'OuterPosition', [0 0 1 1]); % resizes!
        
end

% TODO: create a reset button
function resetPerm(~, ~, gd)
    gd.resetPerm();
    
    % clear plot
    cla(gd.handles.hPlotAxes, 'reset');
    
    %reset inputs
    set(gd.handles.hNumPerms, 'String', '');
    set(gd.handles.hWRange, 'String', '');
    set(gd.handles.hSigLowPerm, 'String', '2.5');
    set(gd.handles.hSigHighPerm, 'String', '97.5');
end

% TODO: create a reset function
function resetPsth(~, ~, gd)
    gd.resetPsth();
    
    % clear plot
    cla(gd.handles.hPlotAxes, 'reset');
    
    % reset inputs
    set(gd.handles.hLagBefore, 'String', '');
    set(gd.handles.hLagAfter, 'String', '');
    set(gd.handles.hNumPermsPsth, 'String', '');
    set(gd.handles.hStartFrameEdit, 'String', '1');
    set(gd.handles.hInclThreshEdit, 'String', '0.2');
    set(gd.handles.hSigLowPsth, 'String', '2.5');
    set(gd.handles.hSigHighPsth, 'String', '97.5');
end

% What to do on closing
function cbCloseGUI(hObj, ~, gd)
    if ~isempty(gd.handles.hWaitBar)
        delete(gd.handles.hWaitBar);
    end
    
    %delete guidata and hobj
    delete(hObj);
end

end