function helpFig(varargin)

W = 200;
H = 200;
dboxPos = getnicedialoglocation([0 0 W H],'pixels');


hMain = figure(...
    'units','pixels',...
    'position',dboxPos,...
    'MenuBar', 'none',...
    'numbertitle','off',...
    'name', 'Help');
