function infoFig(~, ~, about)
%INFOFIG - About window for blinkGUI.m
%

%%
bkgdColor = [.8 .9 1];
W = 275;
H = 250;
dboxPos = getnicedialoglocation([0 0 W H],'pixels');

hMain = figure('name', 'About',...
    'units', 'pixels',...
    'position', dboxPos,...
    'MenuBar', 'none',...
    'numbertitle', 'off',...
    'Color', bkgdColor,...
    'resize', 'off');

set(hMain,'DefaultUicontrolFontName', 'Helvetica',... 
    'DefaultUicontrolFontSize', 15,...
    'DefaultUicontrolFontUnits', 'pixels',...
    'DefaultUicontrolFontWeight', 'normal',...
    'DefaultUicontrolHorizontalAlignment', 'center',...
    'DefaultUicontrolBackgroundColor', bkgdColor);

%Blink Analysis GUI
uicontrol(hMain, 'style', 'text',...
    'String','ReSITE',...
    'FontWeight', 'bold',...
    'FontSize', 24,...
    'Position', [0 200 W 30]);

uicontrol(hMain, 'style', 'text',...
    'String', 'Relative Salience Identified Through Eyeblinks',...
    'FontSize', 12,...
    'Position', [0 180 W 25]);


vertext = {sprintf('Version %s',about.version),...
    sprintf('Released %s',about.releaseDate),...
    ' ',...
    'For support, see [website]'};
    
uicontrol(hMain, 'style', 'text',...
    'String', vertext,...
    'Position', [0 80 W 90]);

writer = {'Written by Carolyn Ranti',...
    'Social Neuroscience Lab',...
    'Marcus Autism Center',...
    'Atlanta, GA'};

uicontrol(hMain, 'style', 'text',...
    'String', writer,...
    'Position', [0 2 W 90]);