function [selection, value] = twoRadioDlg(options)
%
% Two radio buttons in a dialog box.
%
% Written by Carolyn Ranti

%TODO - also pass in parameters such as fontsize, fontname, etc, to have
%this dialog box match the rest of the GUI

radioStrings = options(:,1);
radioValues = options(:,2);

dbox = dialog('Position',[100 100 300 150],...
              'Name','Select data format');
radioGroup = uibuttongroup(dbox,...
    'visible','off',...
    'Units','normalized',...
    'Position',[0 .2 1 .8]);

% Create 2 radio buttons in the button group.
u0 = uicontrol('Style','radiobutton',...
    'String', radioStrings{1},...
    'Value', 1,...
    'Units','normalized',...
    'pos',[.1 .5 .9 .5],...
    'parent',radioGroup,...
    'HandleVisibility','off');
u1 = uicontrol('Style','radiobutton',...
    'String',radioStrings{2},...
    'Value', 2,...'pos',[10 250 100 30],...
    'Units','normalized',...
    'pos',[.1 0 .9 .5],...
    'parent',radioGroup,...
    'HandleVisibility','off');

ok_btn = uicontrol(dbox,'Style','pushbutton',...
                   'String','OK',... 
                   'Units','normalized',...
                   'Position',[0 0 .5 .2],... [ffs+fus ffs+fus btn_wid uh],... 'Tag','ok_btn',...
                   'Callback',{@doOK,radioGroup});

cancel_btn = uicontrol(dbox,'Style','pushbutton',...
                       'String','Cancel',... 
                       'Units','normalized',...
                       'Position',[.5 0 .5 .2],... [ffs+2*fus+btn_wid ffs+fus btn_wid uh],... 'Tag','cancel_btn',...
                       'Callback',{@doCancel,radioGroup});

% Initialize some button group properties.
set(radioGroup,'SelectedObject',[]);  % No selection
set(radioGroup,'Visible','on');


%% OK callback
function doOK(varargin)
    selectionValue = get(get(radioGroup,'SelectedObject'),'Value');
    if ~isempty(selectionValue)
        value = 1;
        disp(radioValues{selectionValue});
        delete(dbox);
    end
end

%% Cancel callback
function doCancel(varargin)
    value = 0;
    selection = [];
    delete(dbox);
end

end